# Generated by Django 3.2.6 on 2021-08-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_shoppinglist_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='shopitem',
            old_name='price',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='name',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.item'),
        ),
    ]
