# Generated by Django 3.2.6 on 2021-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_shoppinglist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
