# Generated by Django 3.2.6 on 2021-08-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_shopitem_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItem',
            new_name='ShoppingListItem',
        ),
    ]
